export const environment = {
  production: true,
  endpoint: "https://projeto-codei-backend-1.onrender.com",
  login: "/api/auth/login",
  register: "/api/auth/register",
  getUser: "/api/auth/user",
  comment: "/api/moments/${id}/comments",
  like: "/api/moments/${id}/like",
  getLike: "/api/moments/${id}/like",
  moments: "/api/moments",
  getMyProfile: "/api/profile/me",
  getProfiles: "/api/profile/",
  getProfileId: "/api/profile/${id}",
  updateProfile: "/api/profile/${id}",
  getFriends: "/api/friends",
  getFriendsById: "/api/friends/${id}",
  addFriend: "/api/friends",
  removeFriend: "/api/friends/${id}",
  getMessages: "/api/message/conversations",
  getMessagesById: "/api/message/${id}",
  sendMessage: "/api/message/send",
  notifications: "/api/notifications",
  markAsRead: "/api/message/read/${id}",
  devicons:
    "https://raw.githubusercontent.com/devicons/devicon/master/devicon.json",
};
